#ifndef CHATTER_LOGIN_DIALOG_DEF_H
#define CHATTER_LOGIN_DIALOG_DEF_H

#define ID_CHATTER_LOGIN_DIALOG 1200

#define ID_EDIT_NAME  1201
#define ID_EDIT_PASS  1202
#define ID_TXT_NAME   1203
#define ID_TXT_PASS   1204

#endif
